<a href="https://colab.research.google.com/github/msj102525/study_python/blob/main/1_1_numpy_tensorflow_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1_1_numpy_tensorflow_pythorch.ipynb
구글 코렙을 이용해서 코드 작성한 첫번째 파일

PyTorch 설치전 : 런타임 메뉴 > 런타임 유형 변경 > GPU 지정\
PyTorch 설치 (매 세션마다 설치 필요함)

In [7]:
!pip3 install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [8]:
!pip3 install torchvision

# Framework Comparison (패키지 비교)

*   Numpy vs Tensorflow vs Pytorch
*   output = x * y + z



In [17]:
import numpy as np
from datetime import datetime

start = datetime.now()

np.random.seed(0) # 랜덤값 발생 고정시킴

N, D = 3, 4

x = np.random.randn(N, D) # 3행 4열 배열에 0 ~ 1 사이의 랜덤값 채움
y = np.random.randn(N, D)
z = np.random.randn(N, D)

a = x * y
b = a + z
c = np.sum(b)

grad_c = 1.0
grad_b = grad_c * np.ones((N, D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_y = grad_a * y
grad_x = grad_a * x

print(grad_x)
print(grad_y)
print(grad_z)

print('연산 처리 시간 : ', datetime.now() - start)


[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
[[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
연산 처리 시간 :  0:00:00.001705


In [8]:
# import tensorflow as tf
import numpy as np
from datetime import datetime

# tf.placeholder() 함수 AttributeError 발생시 해결방법
# tensorflow 2.0 에서는 사용 못 함
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
# ----------------------------------------


In [16]:
start = datetime.now()
print(start)

# 실행 동작을 미리 정의해 놓음
with tf.device('/gpu:0'): # 실행시 gpu 0 사용을 지정함
  x = tf.placeholder(tf.float32)  # 나중에 값을 넣을 공간을 만듦
  y = tf.placeholder(tf.float32)
  z = tf.placeholder(tf.float32)

  a = x * y
  b = a + z
  c = tf.reduce_sum(b)

grad_x, grad_y, grad_z = tf.gradients(c, [x, y, z])

# 준비된 공간에 값을 채우는 설정
with tf.Session() as sess:
  values = {
      x: np.random.randn(N, D),
      y: np.random.randn(N, D),
      z: np.random.randn(N, D)
  }

  out = sess.run([c, grad_x, grad_y, grad_z], feed_dict=values)
  c_val, grad_x_val, grad_y_val, grad_z_val = out

print(grad_x_val)
print(grad_y_val)
print(grad_z_val)

print('연산 처리 시간 : ', datetime.now() - start)

2024-05-28 02:23:01.454414
[[-1.3065269   1.6581306  -0.11816405 -0.6801782 ]
 [ 0.6663831  -0.4607198  -1.3342584  -1.3467175 ]
 [ 0.69377315 -0.15957344 -0.13370156  1.0777438 ]]
[[ 0.68981814  1.3018463  -0.6280876  -0.48102713]
 [ 2.3039167  -1.0600158  -0.1359497   1.1368914 ]
 [ 0.09772497  0.5829537  -0.39944902  0.37005588]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
연산 처리 시간 :  0:00:00.050429


In [27]:
import torch
from torch.autograd import Variable
from datetime import datetime

start = datetime.now()

N, D = 3, 4 # 생략 가능 : 위쪽 셀에서의 선언을 그대로 사용해도 됨

# 자동 미분 계산 클래스 : autograd.Variable
x = Variable(torch.randn(N, D).cuda(), requires_grad=True)
y = Variable(torch.randn(N, D).cuda(), requires_grad=True)
z = Variable(torch.randn(N, D).cuda(), requires_grad=True)

a = x * y
b = a + z
c = torch.sum(b)

# gradient(경사도) 자동 계산 수행
# 기울기(gradient)가 1.0 이라고 가정하고 최종 값인 c 에서
# backward를 통해서 역전파를 해 줍니다.
# c.backward(gradient=torch.cuda.FloatTensor([1.0])) # GPU 버전
c.backward(gradient=torch.tensor(1, dtype=torch.float)) # CPU 버전

print(x.grad)
print(y.grad)
print(z.grad)

print('연산 처리 시간 : ', datetime.now() - start)

tensor([[-1.7628,  0.8301,  0.9345,  0.5174],
        [-1.3685,  0.2514,  0.1901, -1.2232],
        [ 0.8040,  0.7934,  1.0422, -1.3981]], device='cuda:0')
tensor([[-0.8147, -1.2002, -0.3382,  0.3469],
        [-0.6980, -2.1021, -0.5455, -0.0280],
        [-0.8676, -1.1464,  0.1785, -0.2273]], device='cuda:0')
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
연산 처리 시간 :  0:00:00.008644
