<a href="https://colab.research.google.com/github/msj102525/study_python/blob/main/1_2_pytorch_basic_using.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Tensor Basic Usage

- Create Tensor
- indexing, Joining, Slicing
- Initialization
- Math Operations

In [3]:
# 1. Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) --> (0, 1) 사이의 실수형 값을 랜덤값으로 발생함
# sizes : 1차원갯수, 2차원 행렬갯수 등 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x


tensor([[0.4461, 0.3566, 0.1225],
        [0.4108, 0.3746, 0.8097]])

In [ ]:
# torch.randn(sizes) --> Z(0, 1)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
x = torch.randn(2, 3)
x

tensor([[ 0.8167,  0.3060, -1.3034],
        [ 0.7403, -2.2853, -1.6381]])

In [ ]:
# torch.randperm(n) --> permutation of 0 ~ n
x = torch.randperm(5)
# x

tensor([2, 1, 4, 0, 3])

# ** torch 에서 랜덤값으로 텐서 생성 **
1. torch.rand() : 0과 1사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
4. torch.randn_like() : 기존의 텐서를 사용해서 같은 텐서를 생성
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성하는 함
6. torch.randint_like() : 텐서 이용, 같은 텐서 생성
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성

# 3) **Tensor Data Type**

In [4]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2, 3) # size
x

tensor([[2.8026e-45, 0.0000e+00, 3.6969e-19],
        [4.3262e-41, 0.0000e+00, 1.9866e-36]])

In [5]:
x = torch.FloatTensor([12, 35])
x

tensor([12., 35.])

In [6]:
# tensor.type_as(tesnor_type)
# 기존 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

# **4) Numpy to Tensor, Tensor to Numpy**

In [11]:
import numpy as np

# torch.from_numpy(ndarrayy) --> Tensor
x1 = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array([1, 2, 3, 4, 5, 6]))
x2 = torch.from_numpy(x1)
x1, x2

(array([[1, 2, 3],
        [4, 5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [12]:
# torch.numpy() --> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

# **5) Tensor on CPU & GPU**

In [13]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

# **6) Tensor size**

In [18]:
# tensor.size() --> 인덱스값
x = torch.FloatTensor(10, 12, 3, 3)
x.size()[:]

torch.Size([10, 12, 3, 3])

# **2. Indexing, Slicing, Joining**
**1) Indexing**

In [19]:
# torch.index_select(input, dim, index)
x = torch.rand(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3]))

x, out

(tensor([[0.9312, 0.2000, 0.8091],
         [0.8856, 0.3209, 0.8152],
         [0.2108, 0.9687, 0.6061],
         [0.8718, 0.1120, 0.1571]]),
 tensor([[0.9312, 0.2000, 0.8091],
         [0.8718, 0.1120, 0.1571]]))

In [20]:
# python indexing 사용 가능
x[:, 0], x[0, :], x[0:2, 0:2]

(tensor([0.9312, 0.8856, 0.2108, 0.8718]),
 tensor([0.9312, 0.2000, 0.8091]),
 tensor([[0.9312, 0.2000],
         [0.8856, 0.3209]]))

In [22]:
# torch.masked_select(input, mask)
x = torch.randn(2, 3)
mask = torch.BoolTensor([[0, 0, 1], [0, 1, 0]])
out = torch.masked_select(x, mask)

x, mask, out

(tensor([[-0.2548, -0.7212,  0.6541],
         [ 1.6908, -0.1872, -0.2761]]),
 tensor([[False, False,  True],
         [False,  True, False]]),
 tensor([ 0.6541, -0.1872]))

# **2) Joining**

In [27]:
# torch.cat(seq, dim=0)
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
y = torch.FloatTensor([[-1, -2, -3], [-4, -5, -6]])
z1 = torch.cat([x, y], dim=0) # dim=0 (행), 아래에 합쳐짐
z2 = torch.cat([x, y], dim=1) # dim=1 (열), 오른쪽에 합쳐짐

x. y. z1. z2

AttributeError: 'Tensor' object has no attribute 'y'

In [25]:
# torch.stack(sequence, dim=0) --> 새로운 차원으로 추가
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]]) # (2, 3) shape
x_stack = torch.stack([x, x, x, x], dim=0)  # (4, 2, 3) shape

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

# **3) Slicing**

In [28]:
# torch.chunk(tensor, chunks, dim=0)
x_1, x_2 = torch.chunk(z1, 2, dim=0)  # dim=0 이면 행을 2개로 분할
x_1, x_2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]))

In [ ]:
y_1, y_2, y_3 = torch.chunk(z1, 3, dim=1)  # dim=1 이면 열을 3개로 분할
y_1, y_2, y_3

In [29]:
# torch.split(tensor, split_size, dim=0)
x1, x2 = torch.split(z1, 2, dim=0)
y1 = torch.split(z1, 2, dim=1)  # 3개 열을 2개로 분리한 경우

z1, x1, x2, y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 (tensor([[ 1.,  2.],
          [ 4.,  5.],
          [-1., -2.],
          [-4., -5.]]),
  tensor([[ 3.],
          [ 6.],
          [-3.],
          [-6.]])))

# **4) squeezing**

In [30]:
# torch.squeeze(input, dim=None) # 숫자가 1인 차원을 제거

x1 = torch.FloatTensor(10, 1, 3, 14)
# 차원(dimension) 의 개념
# 10 : batch size (데이터 한 묶음당 들어있는 데이터(x, y)쌍의 갯수)
# 1 : channel size
# 3 : with image size
# 14 : height image size

x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 14]), torch.Size([10, 3, 14]))

In [31]:
# torch.unsqueeze(input, dim=None) # 숫자가 1인 차원을 추가
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0) # dim=0 이면 첫번쨰 위치에 추가

x1.size(), x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

# **3. Initialization**

In [33]:
import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3, 4), a=0, b=9) # a에서 b사이의 값으로 초기
x2 = init.normal(torch.FloatTensor(3, 4), std=0.2)  # 표준편차가 0.2 적용 초기화
x3 = init.constant(torch.FloatTensor(3, 4), 3.145)  # 지정된 상수값으로 초기화

x1, x2, x3

<ipython-input-33-f8c383e478f3>:3: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  x1 = init.uniform(torch.FloatTensor(3, 4), a=0, b=9) # a에서 b사이의 값으로 초기
<ipython-input-33-f8c383e478f3>:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  x2 = init.normal(torch.FloatTensor(3, 4), std=0.2)  # 표준편차가 0.2 적용 초기화
<ipython-input-33-f8c383e478f3>:5: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  x3 = init.constant(torch.FloatTensor(3, 4), 3.145)  # 지정된 상수값으로 초기화


(tensor([[2.0789, 6.5818, 4.2441, 8.8385],
         [6.1116, 8.6031, 5.3566, 2.4016],
         [0.9752, 3.0204, 6.0628, 6.8317]]),
 tensor([[ 0.2068, -0.0634, -0.4715,  0.0893],
         [-0.2528, -0.0414, -0.1046,  0.3241],
         [-0.2236, -0.2810,  0.0310,  0.1597]]),
 tensor([[3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450]]))

# **4.Math Operations**
**1) Arithmetic operations**

In [40]:
# torch.add()
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
add = torch.add(x1, x2)
x1, x2, add, x1 + x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]))

In [39]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.add(x1, 10)
x1, x2, x1 + 10, x1 - 10

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[-9., -8., -7.],
         [-6., -5., -4.]]))

In [42]:
# touch.mul() 곱하기
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x3 = torch.mul(x1, x2)
x3, x1 * x2

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [44]:
# touch.div() 나누기
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.div(x1, 5)
x1, x2, x1 / 5

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]))

# **2) Other Math Operations**

In [45]:
# torch.pow(input, exponent)
x1 = torch.FloatTensor(3, 4)

x1, torch.pow(x1, 2), x1 ** 2

(tensor([[ 9.7801e-12,  4.3262e-41,  9.7801e-12,  4.3262e-41],
         [ 4.4842e-44,  0.0000e+00,  1.5695e-43,  0.0000e+00],
         [-6.3210e+08,  7.0065e-45,  9.1477e-41,  1.1771e-43]]),
 tensor([[9.5650e-23, 0.0000e+00, 9.5650e-23, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [3.9955e+17, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[9.5650e-23, 0.0000e+00, 9.5650e-23, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [3.9955e+17, 0.0000e+00, 0.0000e+00, 0.0000e+00]]))

In [46]:
# torch.exp(tensor, out=None)
x1 = torch.FloatTensor(3, 4)
out = torch.exp(x1)

x1, out

(tensor([[9.7800e-12, 4.3262e-41, 9.7800e-12, 4.3262e-41],
         [2.3321e+26, 3.3319e-41, 9.7800e-12, 4.3262e-41],
         [1.7301e+22, 3.3319e-41, 2.7334e+26, 3.3319e-41]]),
 tensor([[1., 1., 1., 1.],
         [inf, 1., 1., 1.],
         [inf, 1., inf, 1.]]))

In [47]:
# torch.log(input, out=None) 자연로그 계산
x1 = torch.FloatTensor(3, 4)
out = torch.log(x1)

x1, out

(tensor([[0.0000e+00, 0.0000e+00, 2.4564e+26, 3.3319e-41],
         [2.7135e+21, 3.3319e-41, 5.7263e-13, 4.3261e-41],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[    -inf,     -inf,  60.7659, -93.2025],
         [ 49.3525, -93.2025, -28.1885, -92.9413],
         [    -inf,     -inf,     -inf,     -inf]]))

# **3) Matrix operation**

In [48]:
# torch.mm(mat1, mat2) --> matrix multiplication (행렬곱)
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
out = torch.mm(x1, x2)

x1, x2, out

(tensor([[ 9.7801e-12,  4.3262e-41,  2.3386e+26,  3.3319e-41],
         [ 4.4842e-44,  0.0000e+00,  8.9683e-44,  0.0000e+00],
         [-1.8720e-16,  3.3323e-41,  0.0000e+00,  1.1755e-38]]),
 tensor([[-6.3060e+08,  7.0065e-45,  1.0930e-43,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  7.2076e+31],
         [ 7.7052e+31,  1.9447e+31,  2.1715e-18,  2.3081e-12,  1.8590e+34],
         [ 7.7767e+31,  1.7181e+19,  1.8990e+28,  1.5766e-19,  1.4587e-19]]),
 tensor([[       inf,        inf, 5.0781e+08, 5.3977e+14,        inf],
         [6.9103e-12, 1.7441e-12, 0.0000e+00, 0.0000e+00, 1.6672e-09],
         [1.0322e-06, 2.0196e-19, 2.2322e-10, 0.0000e+00, 2.4018e-09]]))

In [49]:
# torch.bmm(batch1, batch2) --> batch 행렬곱 연산
# 맨 앞의 batch 는 차원을 유지하면서, 뒤 요소들의 행렬곱 연산

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
out = torch.bmm(x1, x2)

out.size()

torch.Size([10, 3, 5])

In [50]:
# torch.dot(tesnor1, tensor2) : 백터의 내적을 구함

x1 = torch.FloatTensor([1, 2, 3, 4])
x2 = torch.FloatTensor([2, 3, 4, 5])

torch.dot(x1, x2)

tensor(40.)

In [51]:
# torch.t(matrix) : transposed matrix (텐서의 전치 연산)
# 행과 열을 바꿈

x1 = torch.FloatTensor(3, 4)

x1, x1.t()



(tensor([[9.7801e-12, 4.3262e-41, 2.4026e+26, 3.3319e-41],
         [2.6914e+26, 3.3319e-41, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 2.6918e+26, 3.3319e-41]]),
 tensor([[9.7801e-12, 2.6914e+26, 0.0000e+00],
         [4.3262e-41, 3.3319e-41, 0.0000e+00],
         [2.4026e+26, 0.0000e+00, 2.6918e+26],
         [3.3319e-41, 0.0000e+00, 3.3319e-41]]))

In [52]:
# torch.transpose(input, dim_0, dim_1)
# 바꿀 차원을 2개 지정함
# 텐서의 내부 차원간 바꾸기

x1 = torch.FloatTensor(10, 3, 4)

# 1차원과 2차원을 서로 바꿈
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1, 2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [59]:
# torch.eig(input, eigenvectors=Flase)
# 고유값(eigen_value), 고유벡터(eigen_vector) 반환
x1 = torch.FloatTensor(4, 4)

import torch.linalg as linalg
x1, torch.linalg.eig(x1)

(tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31],
         [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
         [7.0367e+22, 2.1715e-18, 6.7996e+22, 1.3236e-08],
         [6.8000e+22, 1.0488e-08, 4.1340e-05, 1.2812e-11]]),
 torch.return_types.linalg_eig(
 eigenvalues=tensor([ 5.0778e+31+0.j, -1.1105e+27+0.j,  1.1126e+27+0.j,  4.6152e+22+0.j]),
 eigenvectors=tensor([[ 1.4035e-09+0.j,  5.7122e-01+0.j,  5.7323e-01+0.j,  1.5237e-01+0.j],
         [ 1.0000e+00+0.j, -8.2080e-01+0.j, -8.1940e-01+0.j, -2.9457e-01+0.j],
         [-1.5137e-15+0.j, -3.3236e-05+0.j,  3.9224e-05+0.j, -9.4340e-01+0.j],
         [-7.2974e-17+0.j, -3.4911e-05+0.j,  3.5101e-05+0.j,  9.2117e-04+0.j]])))