<a href="https://colab.research.google.com/github/msj102525/study_python/blob/main/1_2_pytorch_basic_using.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Tensor Basic Usage

- Create Tensor
- indexing, Joining, Slicing
- Initialization
- Math Operations

In [4]:
# 1. Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) --> (0, 1) 사이의 실수형 값을 랜덤값으로 발생함
# sizes : 1차원갯수, 2차원 행렬갯수 등 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x


tensor([[0.8219, 0.9272, 0.5680],
        [0.7273, 0.1524, 0.8585]])

In [24]:
# torch.randn(sizes) --> Z(0, 1)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
x = torch.randn(2, 3)
x

tensor([[ 0.8167,  0.3060, -1.3034],
        [ 0.7403, -2.2853, -1.6381]])

In [19]:
# torch.randperm(n) --> permutation of 0 ~ n
x = torch.randperm(5)
x

tensor([2, 1, 4, 0, 3])

# ** torch 에서 랜덤값으로 텐서 생성 **
1. torch.rand() : 0과 1사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
4. torch.randn_like() : 기존의 텐서를 사용해서 같은 텐서를 생성
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성하는 함
6. torch.randint_like() : 텐서 이용, 같은 텐서 생성
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성